version: '3.8'

services:
  api_gateway:
    build: 
      context: .
      dockerfile: services/api_gateway/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/rockfall_db
      - PREDICTION_SERVICE_URL=http://prediction_service:8001
      - ALERT_MANAGER_URL=http://alert_manager:8002
    depends_on:
      - db
      - prediction_service
      - alert_manager
      - influxdb
    networks:
      - rockfall_net

  prediction_service:
    build:
      context: .
      dockerfile: services/prediction_service/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/rockfall_db
      - INFLUXDB_URL=http://influxdb:8086
    depends_on:
      - db
      - influxdb
    networks:
      - rockfall_net

  alert_manager:
    build:
      context: .
      dockerfile: services/alert_manager/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/rockfall_db
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_FROM_NUMBER=${TWILIO_FROM_NUMBER}
    depends_on:
      - db
    networks:
      - rockfall_net

  data_collector:
    build:
      context: .
      dockerfile: services/data_collector/Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/rockfall_db
      - INFLUXDB_URL=http://influxdb:8086
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - IRIS_CLIENT_ID=${IRIS_CLIENT_ID}
      - IRIS_CLIENT_SECRET=${IRIS_CLIENT_SECRET}
    depends_on:
      - db
      - influxdb
    networks:
      - rockfall_net

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rockfall_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rockfall_net

  influxdb:
    image: influxdb:2.0
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=rockfall
      - DOCKER_INFLUXDB_INIT_BUCKET=timeseries
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - rockfall_net

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api_gateway:8000
    depends_on:
      - api_gateway
    networks:
      - rockfall_net

volumes:
  postgres_data:
  influxdb_data:

networks:
  rockfall_net:
    driver: bridge
